### ISSUE TITLE
deltaT multi-byte values incorrect

### ISSUE THREAD

**Issue by dghenshaw** [g200kg/midi-dump#1]
In events, DeltaT is a variable length field.  MidiDump incorrectly interprets this for values>127 (i.e. multiple byte fields).
For example hex 87 30 is decimal 7*128+48=944 but midi dump says it is decimal 55.

**Comment by g200kg** [comment]
Thank you. I did not notice.
I fixed it now.

**Comment by dghenshaw** [comment]
Looks good now.
